### ISSUE TITLE
Test doesn't work

### ISSUE THREAD

**Issue by TehcJS** [Astrarre/Amalgamation#5]

**Comment by Devan-Kerman** [comment]
gibe logs

**Comment by TehcJS** [comment]
![image](https://user-images.githubusercontent.com/18603248/147137911-4691b7a3-ee93-488a-af2c-15f570d27885.png)
:help_me:

**Comment by TehcJS** [comment]
it's not even a module

**Comment by TehcJS** [comment]
wait how do i even use this

**Comment by Devan-Kerman** [comment]
it's a detached gradle project it's not a module, right click the build.gradle with intellij and say import as gradle project

**Comment by Devan-Kerman** [comment]
it's basically just a gradle project that just happens to be inside another, they are unrelated to each other

**Comment by TehcJS** [comment]
ir reopen

**Comment by Devan-Kerman** [comment]
documentation more like cringe yate

**Comment by Devan-Kerman** [comment]
i'll document stuff one day:tm:

**Comment by Devan-Kerman** [comment]
first priority is getting it to function

**Comment by TehcJS** [comment]
mojmap doesn't even work lol

**Comment by ramidzkh** [comment]
cope
